name: Deploy Terraform
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    environment: ${{ inputs.action }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Manual Azure CLI Login
        run: |
          echo "Attempting manual Azure CLI login using Service Principal..."
          az login --service-principal \
            --username "${{ secrets.ARM_CLIENT_ID }}" \
            --password "${{ secrets.ARM_CLIENT_SECRET }}" \
            --tenant "${{ secrets.ARM_TENANT_ID }}" \
            --output none # Suppress output for security
          echo "Azure CLI login successful. Setting subscription..."
          az account set --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"
          echo "Subscription set."
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init 
      - name: Execute terraform action
        id: run_action
        run: |
          case "${{ github.event.inputs.action }}" in
            plan)
              cd terraform
              terraform plan -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
              ;;
            apply)
              cd terraform
              terraform apply -auto-approve -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
              ;;
            destroy)
              cd terraform
              terraform destroy -auto-approve -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
              ;;
            *)
              echo "Unknown environment"
              exit 1
              ;;
          esac